# Generated by Django 4.2.6 on 2024-07-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_item_user_name_item_user_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_nam',
            new_name='user_name',
        ),
    ]
